name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      working-directory: ./b.ibs_web
      run: ls && pwd && npm run test
    
    - name: Run ESLint
      working-directory: ./b.ibs_web
      run: npm run lint
    
    - name: Build
      working-directory: ./b.ibs_web
      run: npm run build
    
